### ISSUE TITLE
文件解密之后 文件还是会损坏

### ISSUE THREAD

**Issue by originzyf** [GcsSloop/encrypt#6]
解密之后文件会损坏 请问有什么办法吗

**Comment by GcsSloop** [comment]
加密和解密的方法和参数是一致的？

**Comment by originzyf** [comment]
![tim 20180410111644](https://user-images.githubusercontent.com/17819772/38534414-b511fb34-3cb0-11e8-867b-a8f25428f2df.png)
![tim 20180410111700](https://user-images.githubusercontent.com/17819772/38534416-b6af5b44-3cb0-11e8-9df4-3e5c9f0d40f8.png)
我是先把文件转成byte数组 然后加密 然后生成加密后的文件 然后在反向解密生成文件

**Comment by GcsSloop** [comment]
我验证一下

**Comment by originzyf** [comment]
好的 谢谢啊

**Comment by GcsSloop** [comment]
我也加密了一个 jpg 文件，发现在解密的时候，有部分数据会被错误识别为 padding，因此导致解密错误，临时修复了一下，试试最新版本。

**Comment by originzyf** [comment]
好的 谢谢啊  我试试

**Comment by originzyf** [comment]
已经可以用了 谢谢啊
